#!/bin/sh
#/etc/init.d/feuergis-alice

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
    start)
        exec forever --sourceDir=/home/feuergis/feuergis/alice -p /var/run index.js
        ;;
    stop)
        exec forever stop --sourceDir=/home/feuergis/feuergis/alice index.js
        ;;
    *)
        echo "Usage: /etc/init.d/feuergis-alice {start|stop}"
        exit 1
        ;;
esac

exit 0
