#!/bin/sh
#/etc/init.d/feuergis-bob

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$i" in
    start)
    exec forever --sourceDir=/home/feuergis/feuergis/bob -p /var/run index.js
    ;;
    stop)
    exec forever stop --sourceDir=/home/feuergis/feuergis/bob index.js
    ;;
    *)
    echo "Usage: /etc/init.d/feuergis-bob {start|stop}"
    exit 1
    ;;
esac

exit 0
